### ISSUE TITLE
[BUG] iOS front camera flash can be set from auto to on but not further

### ISSUE THREAD

**Issue by lcuis** [fluttercandies/flutter_wechat_camera_picker#154]
Hello. Thanks a lot for this great plugin!

**Describe the bug**

On iOS, when using the front camera, clicking on the flash once sets the flash from auto to "on" but clicking again keeps the flash set to on. It doesn't lead to permanent, off, auto (again), etc.

**How to reproduce**

1. Run app on iOS device with code mentioned in Additional context to pick a camera image (photo only).
2. Switch to front camera.
3. Click flash to switch from auto to "on".
4. Click flash again to switch from "on" to permanent.

**Expected behavior**

Flash should be set to permanent.

**Effective behavior**

Flash remains "on".

**Screenshots (If contains)**

![image](https://user-images.githubusercontent.com/32125299/210364174-969a4afb-cdf4-421d-ae76-92d12ce9030f.png)

**Version information**

- Device: iPhone SE 2020
- OS: iOS 16.0.3
- Package Version: 3.6.5
- Flutter Version: 3.3.4
- Language: English

**Additional context**

When long press on flash, info pop up says "Flash mode: always" while the flash mode logo indicates "on".
Everything works fine with the same code on Android.
Everything works fine with the back camera.

I was not able to test this on the plugin example app but I would expect the same result.

The code used to pick a camera image (photo only) is the following one:
```dart
                  AssetEntity result;
                  result = await CameraPicker.pickFromCamera(
                    context,
                    locale: Locale("en"),
                    pickerConfig: CameraPickerConfig(
                      textDelegate: CustomCameraPickerDelegate(),
                      resolutionPreset: ResolutionPreset.low,
                    ),
                  );
```

The English text delegate used is the following one ; though, it shouldn't have any impact IMHO as the rest works fine:
```dart
class CustomCameraPickerDelegate extends CameraPickerTextDelegate {
  @override
  String get languageCode => "en";

  @override
  String get confirm => "Confirm";

  @override
  String get shootingTips => "Click to take a picture.";

  @override
  String get shootingWithRecordingTips =>
  "Click to take a picture. Long press to record a video.";

  @override
  String get shootingOnlyRecordingTips => "Long press to record a video.";

  @override
  String get shootingTapRecordingTips =>
      "Tap to record video.";

  @override
  String get loadFailed => "Loading failed";

  @override
  String get sActionManuallyFocusHint => "Manual focus";

  @override
  String get sActionPreviewHint => "Preview";

  @override
  String get sActionRecordHint => "Save";

  @override
  String get sActionShootHint => "Take a picture";

  @override
  String get sActionShootingButtonTooltip => "Shooting button";

  @override
  String get sActionStopRecordingHint => "Stop recording";

  @override
  String sCameraLensDirectionLabel(CameraLensDirection value) {
    switch (value) {
      case CameraLensDirection.back:
        return "Back";
      case CameraLensDirection.front:
        return "Front";
      case CameraLensDirection.external:
        return "External";
      default:        return value.name;
    }
  }

  @override
  String sCameraPreviewLabel(CameraLensDirection value) {
    if (value == null) {
      return null;
    }
    return "Camera preview ${sCameraLensDirectionLabel(value)}";
  }

  @override
  String sFlashModeLabel(FlashMode mode) => "Flash mode: ${mode.name}";

  @override
  String sSwitchCameraLensDirectionLabel(CameraLensDirection value) =>
      "Switch to ${sCameraLensDirectionLabel(value)} camera";

  @override
  String get loading => "Loading";

  @override
  String get saving => "Saving";
}
```

**Comment by lcuis** [comment]
I can confirm the same behavior with the plugin example app (first line: take a photo) on the same device (iPhone SE 2020). I also got the following error log:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(setFlashModeFailed, Device does not support torch mode)
#0      handleErrorWithHandler (package:wechat_camera_picker/src/internals/methods.dart:28:3)
#1      CameraPickerState.switchFlashesMode (package:wechat_camera_picker/src/states/camera_picker_state.dart:391:7)
<asynchronous suspension>
```
