### ISSUE TITLE
安卓偶现空指针异常： java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.stopRepeating()' on a null object reference

### ISSUE THREAD

**Issue by cxw18772827901** [fluttercandies/flutter_wechat_camera_picker#173]
**Describe the bug**

偶现空指针异常：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.stopRepeating()' on a null object reference
        at io.flutter.plugins.camera.Camera.pausePreview(Camera.java:1073)
        at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:344)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
2023-05-25 23:33:17.033 30817-30979/com.example.flutter.im E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'cameras' has already been initialized.
    #0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:192:5)
    #1      CameraPickerState.cameras= (package:wechat_camera_picker/src/states/camera_picker_state.dart:56:38)
    #2      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:274:9)
    <asynchronous suspension>

**How to reproduce**

偶现，暂未发现规律

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by Oliver-WJ** [comment]
I find  same question

**Comment by huangsir0** [comment]
I find same question

**Comment by OnClickListener2048** [comment]
I find same question
