### ISSUE TITLE
[BUG] Video record unstable on Realme c17 (continue from #193)

### ISSUE THREAD

**Issue by heshesh2010** [fluttercandies/flutter_wechat_camera_picker#206]
(https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/193#issue-1872073056)

Hi , just this issue to continue work on #193 as it was closed

**Comment by AlexV525** [comment]
Could you try #216? If it doesn't address the problem, please share logs with exceptions.

**Comment by heshesh2010** [comment]
@AlexV525 , I tested new commit right now on my samsung device and here is the logs so the video record nor working now on my real device samsung

    E  prepare failed: -12
2023-10-26 10:00:35.599 22941-23123 flutter                 com.appedia.siyaq                    E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(videoRecordingFailed, prepare failed:-12)
                                                                                                    #0      CameraController.startVideoRecording (package:camera/src/camera_controller.dart:550:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      CameraPickerState.startRecordingVideo (package:wechat_camera_picker/src/states/camera_picker_state.dart:925:7)
                                                                                                    <asynchronous suspension>
2023-10-26 10:00:35.599 22941-22941 MethodChan...ra_android com.appedia.siyaq                    E  Failed to handle method call
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.MediaRecorder.getSurface()' on a null object reference
                                                                                                    	at io.flutter.plugins.camera.Camera.startCapture(Camera.java:539)
                                                                                                    	at io.flutter.plugins.camera.Camera.startVideoRecording(Camera.java:771)
                                                                                                    	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:122)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-10-26 10:00:35.601 22941-22941 DartMessenger           com.appedia.siyaq                    E  Uncaught exception in binary message listener
                                                                                                    java.lang.IllegalStateException: Reply already submitted
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by AlexV525** [comment]
This seems like a `camera` issue. You may need to checkout the example of `camera` and see if it's reproducible.

**Comment by heshesh2010** [comment]
@AlexV525  tested on example app android version , same results , sometimes working sometimes not and gets stuck version 4.0.3

**Comment by AlexV525** [comment]
Which means it's a `camera` issue. Please submit corresponding issues then.

**Comment by heshesh2010** [comment]
> Which means it's a `camera` issue. Please submit corresponding issues then.

@AlexV525 what u mean by camera issue , the camera is working without any issue on other apps such whatspp , Facebook and so on .

**Comment by AlexV525** [comment]
`camera` means the `camera` package.
