### ISSUE TITLE
[BUG] [Android] camera cannot shoot after app pause(open other app)

### ISSUE THREAD

**Issue by Takapiroid** [fluttercandies/flutter_wechat_camera_picker#50]
### problem
in Android device, camera cannot shoot after  app pause(open other app)

### procedure
1. open this package camera view
2. open other app (or my app pause)
3. back to my app (displayed camera view)
4. shoot, but cannot

### device
Pixel 4a
version: Android12 beta4

### flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)

### Log
```console
W/MessageQueue(13757): Handler (android.os.Handler) {b2650ba} sending message to a Handler on a dead thread
W/MessageQueue(13757): java.lang.IllegalStateException: Handler (android.os.Handler) {b2650ba} sending message to a Handler on a dead thread
W/MessageQueue(13757): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(13757): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(13757): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(13757): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(13757): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue(13757): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2264)
W/MessageQueue(13757): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(CameraDeviceImpl.java:1976)
W/MessageQueue(13757): 	at android.hardware.camera2.ICameraDeviceCallbacks$Stub.onTransact(ICameraDeviceCallbacks.java:160)
W/MessageQueue(13757): 	at android.os.Binder.execTransactInternal(Binder.java:1184)
W/MessageQueue(13757): 	at android.os.Binder.execTransact(Binder.java:1143)
```

help me.

other Android version happen? i dont know... sorry,

**Comment by AlexV525** [comment]
In which version this issue can reproduced? Have you tried the latest one yet?

**Comment by Takapiroid** [comment]
i tried,
wechat_camera_picker: 2.4.1

**Comment by AlexV525** [comment]
AFAIK this is a known issue that related to the camera plugin: https://github.com/flutter/flutter/issues/89352 , and a potential fix at https://github.com/flutter/plugins/pull/4319 .

**Comment by AlexV525** [comment]
Run `flutter pub upgrade` should solve this.
